import React from 'react';
import {
    PlayAreaGrid,
    Pixel,
} from './PlayArea.styles';

class PlayArea extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <PlayAreaGrid>
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
                <Pixel />
            </PlayAreaGrid>
        );
    }
}

export default PlayArea;
